name: Incorrect information or code
description: File a report on incorrect information or code
title: "[Incorrect information or code]: "
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Relevant Context
      render: shell
  - type: input
    id: file
    attributes:
      label: The Source File
    validations:
      required: false
