name: Incorrect information or code
description: File a report on incorrect information or code
title: "[Incorrect information or code]: "
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing this report!
  - type: textarea
    id: context
    attributes:
      label: Relevant Context
      render: shell
  - type: input
    id: file
    attributes:
      label: The Source File
    validations:
      required: false
  - type: textarea
    id: issuedescription
    attributes:
      label: Description of incorrect information/code
      description: Which information or code needs to be corrected?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: proposedfix
    attributes:
      label: Your proposed fix for the incorrect information/code (optional)
      description: How should the incorrect information/code be fixed?
      placeholder: Your proposed fix
      value: ""
    validations:
      required: false