name: Incorrect information or code
description: File a report on incorrect information or code
title: "[Incorrect information or code]: "
labels: ["triage"]
body:
  - type: markdown
    id: context
    attributes:
      value: |
        Use this form to file an issue with an article on [https://www.linode.com/docs/](linode.com/docs).

        - If you would prefer to provide a 1-5 star rating for a guide, a feedback form is linked to from the bottom of each article.
        - A Disqus form is also available at the bottom of each article to discuss it with other readers.
        - For issues with your Akamai/Linode account or resources, please [contact customer support](https://www.linode.com/docs/products/platform/get-started/guides/support/#contact-customer-support).
        - For other cloud computing discussions not related to specific Linode documentation, visit the [Community Questions forum](https://www.linode.com/community/questions/).

        Thank you for filing your report!
  - type: input
    id: file
    attributes:
      label: The Source File
    validations:
      required: false
  - type: textarea
    id: context
    description: Relevant section of article
    attributes:
      label: Quoted material from article
      placeholder: Copy and paste relevant section of article here
      value: "test"
      render: shell
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Issue category
      description: What category best describes the issue?
      options:
        - Information incorrect or outdated
        - Sample code or command produces error
        - Unclear instructions or missing steps
        - Typo, spelling, or grammar issue
        - Other
      default: 4
    validations:
      required: true
