name: Incorrect information or code
description: File a report on incorrect information or code
title: "[Incorrect information or code]: "
labels: ["triage"]
body:
  - type: markdown
    id: context
    attributes:
      value: |
        Thank you for filing this report!
  - type: input
    id: file
    attributes:
      label: The Source File
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: issuedescription
    attributes:
      label: Description of incorrect information
      description: Which information or code needs to be corrected
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: proposedfix
    attributes:
      label: Your proposed fix for the incorrect information
      description: How should the incorrect information be fixed
      placeholder: Your proposed fix
      value: "a bug happened, fix"
    validations:
      required: false
